# GetSensorsCalibration ; service intended for a BNO08x IMU
---
int8 calibration_config   # Calibration configuration, indicates the calibratio config of the sensors
                          # 1 : Accel, 2 : Gyro, 4 : Mag, 8 : Planar
                          # Values can be combined/added, i.e. 3 = 1 + 2 = Accel and Gyro
bool success              # True if the call succeeded, false otherwise
string status_message     # Details about success
